baseURL = 'https://Dragon-Tuncay.github.io/CTS-Writeups/'
languageCode = 'en-us'
title = 'CTS Writeups'
theme = 'terminal'

[params]
  defaultTheme = "dark"
  logoText = "root@blog:~#"
  contentTypeName = "posts"
