baseURL = 'https://dragon-tuncay.github.io/CTF-Writeups/'
languageCode = 'en-us'
title = 'CTF Writeups'
theme = 'terminal'

[params]
  defaultTheme = "dark"
  logoText = "root@blog:~#"
  contentTypeName = "posts"
